name: Merge upstream branches
on:
  push:
  schedule:
    - cron:  '0 3,23 * * *'
  watch:
    types: [started]
jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'name'
          git config --global user.email 'name@email.com'
          git pull --unshallow
          git remote add upstream https://github.com/NeitherCandiDa/QL_TimingScript.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
          git fetch upstream --tags
          git push --tags
